services:
  mysql:
    image: mysql:8.0
    container_name: brillo_mall_api_datasource
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
    networks:
      - brillo_mall_api-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    container_name: brillo_mall_api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - brillo_mall_api-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brillo_mall_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Keys directory
      - GENERATED_KEYS_DIRECTORY=/app/credentials/keys
      # Spring datasource for MySQL
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver

    ports:
      - "8001:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - brillo_mall_api-network

networks:
  brillo_mall_api-network:
    driver: bridge

volumes:
  mysql_data_dev:
  redis_data_dev:
